#################################################################
## Global Configuration
#################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

#################################################################
## API and dashboard configuration
#################################################################
api:
  dashboard: true
  insecure: false

#################################################################
## Traefik Logging
#################################################################
# Log level
log:
  level: DEBUG

# Access log
accessLog:
  filePath: "/logs/access.log" # Optional: Define the file where logs are written (default: stdout)
  format: json                 # Optional: Set log format (default is "common", also supports "json")
  fields:
    defaultMode: keep          # Optional: Control which fields to keep or drop
    names:
      "ClientAddr": drop       # Drop specific fields like ClientAddr
      "ClientHost": keep       # Keep specific fields like ClientHost

#################################################################
## Entrypoint
#################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

#################################################################
## Providers
#################################################################
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

#################################################################
## DNS Challenge
#################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: joergoertel@proton.me
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: digitalocean
        delayBeforeCheck: 0